-- ============================================================================
-- TRAINING SCHEMA DEPRECATED & REMOVED
-- Training tables and features have been removed from the database schema.
-- All learning content is now managed under the courses schema.
-- ============================================================================
