export const SUGGESTED_TAGS = [
  "JavaScript",
  "TypeScript",
  "React",
  "Next.js",
  "Node.js",
  "Python",
  "Java",
  "C++",
  "C#",
  "PHP",
  "Ruby",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "Django",
  "Flask",
  "Express",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "SQL",
  "PostgreSQL",
  "MongoDB",
  "MySQL",
  "Redis",
  "Machine Learning",
  "Deep Learning",
  "Artificial Intelligence",
  "Data Science",
  "Data Analysis",
  "Big Data",
  "Pandas",
  "NumPy",
  "Computer Vision",
  "NLP",
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "GCP",
  "Cloud Computing",
  "DevOps",
  "Git",
  "GitHub",
  "CI/CD",
  "Cybersecurity",
  "Networking",
  "Blockchain",
  "Web3",
  "API",
  "REST",
  "GraphQL",
  "Microservices",
  "Mobile Development",
  "Android",
  "iOS",
  "Flutter",
  "React Native",
  "UI/UX",
  "Figma",
  "Graphic Design",
  "Game Development",
  "Unity",
  "Digital Marketing",
  "SEO",
  "Social Media",
  "Finance",
  "Accounting",
  "Excel",
  "Project Management",
  "Leadership",
  "Communication",
  "Interview Prep",
] as const;

export const SUGGESTED_CATEGORIES = [
  "Programming",
  "Web Development",
  "Mobile Development",
  "Data Science",
  "Machine Learning & AI",
  "DevOps & Cloud",
  "Cybersecurity",
  "Networking",
  "Database Design",
  "Software Testing",
  "Game Development",
  "Blockchain & Web3",
  "Design & UI/UX",
  "Business & Finance",
  "Marketing",
  "Personal Development",
  "Photography & Video",
  "Music & Audio",
  "Language Learning",
  "Health & Fitness",
] as const;
